version: "3"

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
      - "5001:5000"
    environment:
      REDIS_ADDRESS: redis:6379  # redis 缓存
      MICRO_SERVER_ADDRESS: ":5000"  # go-micro 服务地址，用于服务之间的调用
      MICRO_REGISTRY: mdns
    depends_on:
      - user-service
  # 这个是一个container啊，微服务最牛逼的应该就是跨container
  user-service:
    build: ./user
    ports:
      - "5000:5000"
    environment:
      MONGO_ADDRESS: mongodb://mongo:27017
      MICRO_SERVER_ADDRESS: ":5000"  # go-micro 服务地址，用于服务之间的调用
      MICRO_REGISTRY: mdns
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
#  docker run -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=`docker-machine ip \`docker-machine active\`` --env ADVERTISED_PORT=9092 spotify/kafka
# 我用docker run 启动项目是没有任何问题的，但是换成docker-compose之后就出现问题了，一直循环报错
#  https://medium:com/@marcelo:hossomi/running-kafka-in-docker-machine-64d1501d6f0b
# 根据这篇文章来说的话，这个参数设置不明确，还是使用之前的wurstmeister/zookeeper 这个比较好
  spotify-kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: 192.168.99.100
      ADVERTISED_PORT: 9092
  kafka-manager:
    image: hlebalbau/kafka-manager:1.3.3.16
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: 192.168.99.100


