version: "3"

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
      - "5001:5000"
    environment:
      REDIS_ADDRESS: redis:6379  # redis 缓存
      MICRO_SERVER_ADDRESS: ":5000"  # go-micro 服务地址，用于服务之间的调用
      MICRO_REGISTRY: mdns
    depends_on:
      - user-service

  user-service:
    build: ./user
    ports:
      - "5000:5000"
    environment:
      MONGO_ADDRESS: mongodb://mongo:27017
      MICRO_SERVER_ADDRESS: ":5000"  # go-micro 服务地址，用于服务之间的调用
      MICRO_REGISTRY: mdns
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"