version: '3'
services:
  spotify-kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: 192.168.99.100
      ADVERTISED_PORT: 9092
